### ISSUE TITLE
Mixed-up button classes

### ISSUE THREAD

**Issue by Kartm** [nostalgic-css/NES.css#113]
I'm trying to use your framework on my site.
When I try to set styles of my buttons just like on your site, they have the wrong appearance.
For example, <button class="btn is-success"> looks like primary button, and <button class="btn is-primary"> gives me success button. I'm using version 0.0.2, just like in the example page.

**Comment by evexoio** [comment]
@Kartm can you please share more info? what's the website url if you don't mind 🙏

**Comment by Kartm** [comment]
@evexoio All the code is in our repository: [link](https://github.com/VengelStudio/hangman)
The buttons are in the index.html file, lines 39 and 47.

**Comment by BcRikko** [comment]
I have not published many changes to npm yet, sorry 😢 
so, this css is old → https://unpkg.com/nes.css@0.0.2/css/nes.min.css

Could you import css file in `develop` until we publish the latest version to npm. 🙏

**Comment by Kartm** [comment]
That solves the issue. Will do. Thanks!
