### ISSUE TITLE
Responsive inputs

### ISSUE THREAD

**Issue by 4k1k0** [nostalgic-css/NES.css#124]
Hello. :hand: 

I'm using ness.css v0.0.2 from 

    https://unpkg.com/nes.css@0.0.2/css/nes.min.css

And I noticed that the inputs are not responsive and in some cases wider thant their containers.

![Screenshot](https://i.imgur.com/OPGptjf.png "Screenshot")

This can be solved setting `width: 100%` in the `.input` class, but I noticed that it [already use `max-width: 100%`.](https://github.com/nostalgic-css/NES.css/blob/ac136794133f8e5cb70b09993e40ff8561b2bda0/scss/form/inputs.scss#L12).

Thanks.

related to #8

**Comment by evexoio** [comment]
Hey @4k1k0, we're sorry our package at unpkg.com is outdated. we're releasing soon btw. 🙈

**Comment by 4k1k0** [comment]
Hello @evexoio thank you for your answer. At first I thought that the `npm build` failed because I got an error in the terminal, but it worked great. Thanks! :+1:

**Comment by BcRikko** [comment]
I merged #135
