### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by 4k1k0** [nostalgic-css/NES.css#139]
Hello, :hand: 

I noticed that the Press Start 2P font it's not only for english language. It has support for the latin alphabet and you can use it with characters that are not in english but they are in spanish.

![Font](https://i.imgur.com/BbneKlP.png "Font")

:smiley:

**Comment by evexoio** [comment]
@4k1k0 Nice finding.

I'm assuming you didn't have to search for how to make latin work and it worked right away.
I'm closing the issue because in `README.md`, `Press Start 2P` is said to be `Default` language and `English` language. so nothing to change there. 🙌
