### ISSUE TITLE
weird rendering of checkbox on Chrome 70.x on OSX

### ISSUE THREAD

**Issue by alanrsoares** [nostalgic-css/NES.css#146]
![image](https://user-images.githubusercontent.com/273334/49702859-72ee1400-fc62-11e8-8024-b408a2d61ac5.png)

**Comment by jjspace** [comment]
I am unable to reproduce this on Chrome 70 on OSX. Which version of the framework are you using? Are you looking at the hosted example?

**Comment by evexoio** [comment]
![cantrepro](https://user-images.githubusercontent.com/12014839/49703915-f03e6800-fc13-11e8-9922-c88f66705cbd.gif)

**Comment by BcRikko** [comment]
This issue may be the same as #8 🤔

**Comment by evexoio** [comment]
@alanrsoares We can't reproduce this bug, if you were able to provide reproducible steps please comment them and I will reopen the issue. 🙌
