### ISSUE TITLE
Use is-empty instead of is-transparent

### ISSUE THREAD

**Issue by BcRikko** [nostalgic-css/NES.css#148]
All other icons use `is-empty` 🙏
I want to unify to `is-empty`
https://github.com/nostalgic-css/NES.css/pull/147#issuecomment-445579615

**Comment by 4k1k0** [comment]
I agree. The reason why I used `is-transparent` instead of `is-empty` Is because there's already an `is-empty` class declared.

**Comment by evexoio** [comment]
@peterblazejewicz yep, thats right.

Thanks 🙏
