### ISSUE TITLE
<select> component

### ISSUE THREAD

**Issue by 4k1k0** [nostalgic-css/NES.css#152]
Hello.

I would like to see a `<select>` component in the framework.

I made this but I'm not very confident about the desing. What do you think? Should I make a pull request?

![captura de pantalla_2018-12-09_20-20-03](https://user-images.githubusercontent.com/3821782/49707268-34b80c80-fbf0-11e8-93a4-bf74e541bb02.png)

Thanks.

**Comment by BcRikko** [comment]
Great 🎉 

Could you make four corners missing? like below 🤔 
![2018-12-10 11 46 44](https://user-images.githubusercontent.com/5305599/49708044-48f01e00-fc71-11e8-9013-ca9d6e5fb82a.png)

and Could you pixelize `▼`? like below 🤔 
![2018-12-10 11 49 05](https://user-images.githubusercontent.com/5305599/49708129-9e2c2f80-fc71-11e8-8571-7515826c1552.png)

**Comment by 4k1k0** [comment]
What do you think? 
![captura de pantalla_2018-12-09_21-12-11](https://user-images.githubusercontent.com/3821782/49708878-24eff680-fbf7-11e8-8b0f-a778464d69ff.png)

**Comment by BcRikko** [comment]
like this 😆 
![2018-12-10 12 16 37](https://user-images.githubusercontent.com/5305599/49708974-763ecb00-fc75-11e8-84a2-11bce8dedad5.png)

**Comment by 4k1k0** [comment]
Oh my mistake I used the wrong mixing.
![captura de pantalla_2018-12-09_21-18-43](https://user-images.githubusercontent.com/3821782/49709039-0b02e380-fbf8-11e8-81ad-340e674e5501.png)

**Comment by BcRikko** [comment]
oh, great 😆 🎉

**Comment by cabaalexander** [comment]
<3

**Comment by BcRikko** [comment]
sorry, there is no roadmap. 😢 

I just came up with following elements. 🤔 

* `<input type="range">`
* `<ul>〜</ul>`

**Comment by trezy** [comment]
@4k1k0, I see that you deleted the branch that you were originally using to create this component. Are you still planning on making a PR for it at some point?

**Comment by 4k1k0** [comment]
@trezy oh sorry, i didn't realise i deleted the branch. 🙇 I will check it out 😄

**Comment by trezy** [comment]
@Divoolej that looks fantastic! It looks like @4k1k0 is having some issues with getting `<select />` styles added to the repo, so if you wanted to make a PR to add these styles I think we'd all be pretty stoked about it. 😁

**Comment by Divoolej** [comment]
Thanks @trezy 😄 There you go! -> https://github.com/nostalgic-css/NES.css/pull/217 :)
