### ISSUE TITLE
Feature request: Avatar component

### ISSUE THREAD

**Issue by guastallaigor** [nostalgic-css/NES.css#153]
I think it would be good if we had a avatar component, so I made this: 

![image](https://user-images.githubusercontent.com/22016005/49707515-ac972e80-fc12-11e8-9819-e26d172f5b3f.png)

This component has

Classes to change size:

1. `is-small`
2. `is-medium`
3. `is-large`

Classes to change format:

1. `is-bordered`
2. `is-rounded`

Classes to change color:

1. `is-primary`
2. `is-success`
3. `is-error`
4. `is-warning`
5. `is-default`

This classes can be used in any combination necessary.
What do you guys think? :thinking:

**Comment by BcRikko** [comment]
😆 :+1: 

I think Avatar does not need many options. :thinking: 
I think that it's unlikely that avatar will reflect the color of the status or using avatars with borders 🤔 

but it's good the following classes 👍 
* is-small
* is-medium
* is-large
* is-rounded

**Comment by guastallaigor** [comment]
Okay I understand :smile: 
What about this?

![image](https://user-images.githubusercontent.com/22016005/49723712-a7f06b80-fc4e-11e8-8581-9cd40d4a8a7a.png)

Do I continue to use the gravatar image? I didn't want to put a new one insde the project.
