### ISSUE TITLE
Inconsistent class container vs table

### ISSUE THREAD

**Issue by guastallaigor** [nostalgic-css/NES.css#178]
Table has class is `is-centered`, while container has class `is-center`

![image](https://user-images.githubusercontent.com/22016005/49861413-e9b21b00-fde2-11e8-9346-f1564c6cacca.png)

![image](https://user-images.githubusercontent.com/22016005/49861437-f898cd80-fde2-11e8-8a42-d3754d51a097.png)

Maybe it's better to change one? :thinking:

**Comment by BcRikko** [comment]
`is-centered` +1
