### ISSUE TITLE
Implementation of <ul> Lists

### ISSUE THREAD

**Issue by panoramix360** [nostalgic-css/NES.css#179]
I'm making `<ul>` lists implementation, and will use this issue to PR.

As soon as I have some prototype I'll post here!

**Comment by panoramix360** [comment]
I already made these two examples, what do you guys think?

![image](https://user-images.githubusercontent.com/2154092/49902170-51e81780-fe4a-11e8-89e1-09b81ebf03dc.png)

**Comment by BcRikko** [comment]
I prefer `◆` :heart_eyes: 

because, `▶` is similar to the Radio button. :thinking: 
and `>` is similar to the Blockquote :thinking:

**Comment by panoramix360** [comment]
Did you have another idea for another icon?

**Comment by panoramix360** [comment]
Maybe haha, I just followed the convention!

But ok! I already put it on storybook, I'll make a PR 😀

**Comment by panoramix360** [comment]
PR on develop #182
