### ISSUE TITLE
[Suggestion] Create a component/class doc

### ISSUE THREAD

**Issue by guastallaigor** [nostalgic-css/NES.css#180]
We don't have anywhere in the framework each class each component have, aswell the HTML example for that. So now everyone has to pretty much check the code, or inspect the element using devtools.

So here is my suggestions for this:

- Add next to each component inside `index.html` the HTML that was used for making that component

This is going to make `index.html` larger, so we have maybe compact some of the examples, or create a sidebar that has a link to each component, so the user don't have to scroll down so much.

- Create a document separated from index.html that has all of that information

And a link for that document/component inside `index.html`.

- Add a click inside each component in `index.html` or a button near each component that copy the HTML used, or only the classes.

This will make easier for the users, and faster, even for us sometimes. But we will need to use some JavaScript.

What do you guys think? :thinking:

**Comment by trezy** [comment]
Hey @guastallaigor, I do love the idea of making the website more helpful for users of the framework. However, I'd love to see us go more in the direction of Bootstrap's documentation, where we have pages for individual components, as well as code examples and such. That may just be me, though. Most of our components aren't that complicated, but some of them (like containers) have several variations.

Another option would be to use something like [Gitbook][gitbook], and we could just create Markdown files with information on each component. Something like [`semantic-release`'s][semantic-release-gitbook] is a good example of what I'd like us to end up with. I have created an organization for us on Gitbook and requested the open source license so we would get unlimited spaces, but I figured there wasn't a point to fully setting it up if we decide to go another route.

[gitbook]: https://gitbook.io
[semantic-release-gitbook]: https://semantic-release.gitbook.io/semantic-release/

**Comment by guastallaigor** [comment]
> Hey @guastallaigor, I do love the idea of making the website more helpful for users of the framework. However, I'd love to see us go more in the direction of Bootstrap's documentation, where we have pages for individual components, as well as code examples and such. That may just be me, though. Most of our components aren't that complicated, but some of them (like containers) have several variations.

That would be great though, specially if we add more variations in the future for each component, but that would mean a major refactor in the `README.md`, so the other members would have to agree on this, but in my opinion this is a good move.

> Another option would be to use something like Gitbook, and we could just create Markdown files with information on each component. Something like semantic-release's is a good example of what I'd like us to end up with. I have created an organization for us on Gitbook and requested the open source license so we would get unlimited spaces, but I figured there wasn't a point to fully setting it up if we decide to go another route.

This is also good, both the ideas are, I'm onboard on either of one. I think having this doc is a major addition to the framework and for some users could turn into a necessity, just let me know when we are going to start it 📜

**Comment by guastallaigor** [comment]
I will close this for now because the demo was refactored and LGTM in my opinion.
If we add a lot more components we could do another refactor, but right now it's fine.
