### ISSUE TITLE
Add Browserlist

### ISSUE THREAD

**Issue by jjspace** [nostalgic-css/NES.css#193]
Add `.browserlistrc` file or `browserlist` key in package.json to specify the target versions of browsers that this framework will work with. This will act as a configuration for Autoprefixer as specified [here](https://github.com/postcss/autoprefixer#browsers). This would also specify for contributors and consumers alike which browsers we support. For contributors it would let us know what css properties we can and cant use through the use of tools like [caniuse.com](https://caniuse.com/). For consumers that might already have a target browserlist in mind it would let them know up front if we support everything they would need to support. 

The biggest reason for this, and why I bring it up, is are we supporting IE?

**Comment by BcRikko** [comment]
We already use browserlist. 👍 
https://github.com/nostalgic-css/NES.css/blob/ac136794133f8e5cb70b09993e40ff8561b2bda0/package.json#L56-L58

so I think that it will probably work on IE.
but IE has been untested because I have no environment to test. 😇
