### ISSUE TITLE
Bug: Not working on Safari IOS 12.1

### ISSUE THREAD

**Issue by guastallaigor** [nostalgic-css/NES.css#195]
**Describe the bug**
I've just tested on my iphone and the framework is not working on it.

**To Reproduce**
Open https://nostalgic-css.github.io/NES.css/ on Safari in an IOS 12.1

**Expected behavior**
To work and run smoothly

**Demonstration**
![screenrecording_121720182353](https://user-images.githubusercontent.com/22016005/50127241-89463200-0257-11e9-813a-59df0d14022a.gif)

**Environment**

**OS:** IOS 12.1 (16B92)
**Browser:** Safari
**Build environment (i.e. NodeJS):** N/A

**Suggestion(s) for fixing this issue**
Not sure yet. Maybe check again after the release and try some things

**Additional context**
Cellphone used: Iphone 6S

**Comment by BcRikko** [comment]
I think that it is probably fixed 🤔 
https://github.com/nostalgic-css/NES.css/issues/72
https://github.com/nostalgic-css/NES.css/pull/75

**Comment by guastallaigor** [comment]
Yeah my bad, working great on release :100: , closing this.
