### ISSUE TITLE
Add badges component

### ISSUE THREAD

**Issue by guastallaigor** [nostalgic-css/NES.css#211]
**Is your feature request related to a problem? Please describe.**
Add a badges component kind of like github has but 8bit-like

**Describe the solution you'd like**

First draft

![screencast-localhost-6006-2018 12 18-21-39-49](https://user-images.githubusercontent.com/22016005/50189787-dedd1600-030d-11e9-86ec-c64b36655f39.gif)

**Describe alternatives you've considered**
Not adding this or changing it to other classes like closable (with an close icon) or other things

**Additional context**
Up to this moment the badges must have two sides, a first and black one and the other one changes color. Suggestions are welcome.

**Comment by guastallaigor** [comment]
Second draft, added hability to change left/right side

![screencast-localhost-6006-2018 12 18-22-21-09](https://user-images.githubusercontent.com/22016005/50191090-4ba6df00-0313-11e9-88e0-ac0dbceca588.gif)

**Comment by BcRikko** [comment]
Sounds great 👍 

We might like to use a simple badge like the image below. 🤔 
![badge](https://user-images.githubusercontent.com/5305599/50192186-9a389580-0374-11e9-9b9e-274d0699bef0.png)

Could you do something like the following? 🤔 
```html
<span class="nes-badge">10</span>

<!-- class name and elements are provisional -->
<span class="nes-badge is-splited is-primary">
  <label>npm</label>
  <span>1.0.0</span>
</span>
```

**Comment by jjspace** [comment]
I like the idea and they look good. However I'm curious about where someone might use a two toned badge like this outside of the badges in say a Github README. Where else might it be used?

Regardless I think this could also be a good starting point/inspiration for [button group](https://foundation.zurb.com/sites/docs/v/5.5.3/components/button_groups.html) or radio group.

**Comment by guastallaigor** [comment]
Thank you for your feedback, I will try to improve this in the next few days :paintbrush:
