### ISSUE TITLE
Form style folder structure

### ISSUE THREAD

**Issue by jjspace** [nostalgic-css/NES.css#219]
**Is your feature request related to a problem? Please describe.**

The problem is very minor but I noticed that we have a directory for form styles which includes styles for inputs and selects. However the styles for radios, checkboxes and buttons are located under the elements directory.

**Describe the solution you'd like**

Move the radio, checkbox and button styles into the form directory as these are primarily form/user input elements.

**Describe alternatives you've considered**

Button could potentially go either way, stay in elements or move to forms but I feel it would be better in forms.

**Comment by BcRikko** [comment]
How about this? 🤔 
I referred to [the document of bulma](https://bulma.io/documentation/). 🔍👀 
```
|- elements
|    |- buttons.scss
|- form
     |- inputs.scss
     |- radios.scss
     |- checkboxes.scss
     |- selects.scss
```

**Comment by jjspace** [comment]
Yes that's exactly what I had in mind. I just wasn't sure about `button.scss` It's kind of a form element in that it's a user input but it's also used more generally than in forms. I can see it in either folder so it's up to you.
