### ISSUE TITLE
希望增加中文字体

### ISSUE THREAD

**Issue by qiaohaoforever** [nostalgic-css/NES.css#220]

**Comment by BcRikko** [comment]
Please create using the Issue template. 🙏 

and we are not developing fonts.
We only add it to the fonts section, is that alright? 🤔 
https://github.com/nostalgic-css/NES.css#fonts

**Comment by HFO4** [comment]
You can try this
https://github.com/SolidZORO/zpix-pixel-font

**Comment by df7c5117** [comment]
And you can try 方正点阵冯简体 （for non-commercial use only）

**Comment by BcRikko** [comment]
Close this issue. Please reopen it if you need. 🙏
