### ISSUE TITLE
something is wrong with cdn?

### ISSUE THREAD

**Issue by diomed** [nostalgic-css/NES.css#227]
https://codepen.io/diomed/pen/dwXYKQ

despite including latest version from unpkg CDN
something's off, and styling of nes.css doesn't really show.

any ideas?

**Comment by guastallaigor** [comment]
Hello @diomed. Please, check out this issue #6 and PR #82. 

We added a `nes` prefix to all of our classes mainly to avoid compatibility issues with other frameworks, so your code isn't working because of that.
Try adding it in all of your classes and see if the result is as expected.
Thank you.

**Comment by trezy** [comment]
@diomed If this doesn't solve your issue, please comment and we'll reopen your issue.

**Comment by BcRikko** [comment]
If you want to use the old NES.css, you can use `https://unpkg.com/nes.css@0.0.2/css/nes.min.css` 👍
