### ISSUE TITLE
Should we standardize our round corners?

### ISSUE THREAD

**Issue by trezy** [nostalgic-css/NES.css#230]
**Is your feature request related to a problem? Please describe.**
Currently we have components that have rounded corners by default (`.nes-balloon`), and we have other components that are only rounded if they receive the `.is-rounded` class (`.nes-container`, `.nes-dialog`).

Personally, I think we should round all of those corners by default, but I'm open to hearing other arguments.

**Comment by UltraCakeBakery** [comment]
Personally, i think everything should be squared by default.

**Comment by evexoio** [comment]
> Personally, I think we should round all of those corners by default, but I'm open to hearing other arguments.

I agree

**Comment by BcRikko** [comment]
+1 :+1:

**Comment by JABedford** [comment]
Squared by default sounds like a good decision.

**Comment by BcRikko** [comment]
I think the square is good by default 👍
