### ISSUE TITLE
Bug: Borders is not responsive anymore

### ISSUE THREAD

**Issue by guastallaigor** [nostalgic-css/NES.css#244]
**Describe the bug**
The borders has a few bugs in some resolutions. It's hard to explain but is easy to show, see Screenshots below:

**To Reproduce**
1. Go to the `develop` branch;
2. Change the line 17 of the `index.html` file to `<link href="./css/nes.min.css" rel="stylesheet" />`;
3. Run `npm run build`;
4. You can use something like `php -S localhost:4167`;
5. Check localhost:4167;
6. Zoom in and out and see that this bug happens.

**Expected behavior**
Nothing happened with the borders by changing the resolution/zoom.

**Screenshots**
![image](https://user-images.githubusercontent.com/22016005/50693088-15f53c00-101d-11e9-8914-0dd1baf4ac14.png)

![image](https://user-images.githubusercontent.com/22016005/50693098-1e4d7700-101d-11e9-9b07-a2252455f2db.png)

![image](https://user-images.githubusercontent.com/22016005/50693105-23aac180-101d-11e9-913c-d8bca09af3f4.png)

![image](https://user-images.githubusercontent.com/22016005/50693109-29080c00-101d-11e9-8abe-8a4516e1206c.png)

![image](https://user-images.githubusercontent.com/22016005/50693118-31604700-101d-11e9-8c4c-f4e6cf892a33.png)

![image](https://user-images.githubusercontent.com/22016005/50693126-34f3ce00-101d-11e9-83ab-5b8cd841e466.png)

**Environment:**
 - OS: Ubuntu 16.04 / Ubuntu 18.10 (test it on both)
 - Browser: Google Chrome Version 71.0.3578.98 64 bits
 - Build environment (i.e. NodeJS): v10.15.0

**Suggestion(s) for fixing this issue**
I've no ideia how to fix it. Only solution I see is reverting the borders back for now before the next release.

**Additional context**
In master this is not happening.

**Comment by BcRikko** [comment]
Maybe this is related to #72 .
What is set for `-webkit-font-smoothing: antialiased;`? 🤔

**Comment by BcRikko** [comment]
I fixed border bugs #261 
Did you reproduce the bug yet? 🤔

**Comment by guastallaigor** [comment]
This is happening only when I zoom in and out in **develop**:

**Example when I zoom in (150%)**

![image](https://user-images.githubusercontent.com/22016005/52128079-21875300-261b-11e9-98f2-0d57a72acecc.png)

**Example when I zoom out (75%)**

![image](https://user-images.githubusercontent.com/22016005/52128145-48458980-261b-11e9-992d-05c215cc5ba7.png)

Chrome: Version 72.0.3626.81 64 bits

**Note:** This isn't happening in Firefox.

**Comment by BcRikko** [comment]
Thanks 🙇 
It's reproduce when zooming in Chrome. I got it 👍 
I'll check and fix again 🔧

**Comment by BcRikko** [comment]
When I set `space` to `image-border-repeat`, it was a little better. 🤔 
But it is not perfect. 😭 

### Chrome 72 / zoom 150%

![2019-02-05 20 37 34](https://user-images.githubusercontent.com/5305599/52271032-e9b73d00-2985-11e9-9b89-ee09f5368161.png)
![2019-02-05 20 37 43](https://user-images.githubusercontent.com/5305599/52271033-e9b73d00-2985-11e9-9aa5-50f6c2eea50e.png)

**Comment by guastallaigor** [comment]
This is way better now than it was before. It is not breaking the layout or anything like that.

Yes, it's not perfect but good enough for me, because I'm not even sure if this could be better.
If you want to make a PR with this I'm ok with that :+1:

**Comment by BcRikko** [comment]
I see 😆 
I'll make a PR. 🚀

**Comment by deepPhong** [comment]
I'm still having this issue on your demo website, the borders don't scale well to zooming in Chrome (I'm on Ubuntu 18.04)

**Comment by guastallaigor** [comment]
Yes, I'm sorry about this @deepPhong. 
The idea is to fix this issue again in #319.
Ref #317.

**Comment by deepPhong** [comment]
Oh no I'm fine, I didn't see it was already planned for a fix and just wanted you guys to know. Cheers and keep up the good work
