### ISSUE TITLE
[Enhancement]Icons-Heart-Half-Empty

### ISSUE THREAD

**Issue by shawnhill121** [nostalgic-css/NES.css#246]
**Is your feature request related to a problem? Please describe.**
I felt a half-empty heart icon would be a nice addition.

**Describe the solution you'd like**
An icon for displaying a heart half empty.

**Describe alternatives you've considered**
None.
**Additional context**
I will create this icon and add it to the project.

**Comment by BcRikko** [comment]
ref #247

**Comment by BcRikko** [comment]
ref #389
