### ISSUE TITLE
Dark mode for checkbox

### ISSUE THREAD

**Issue by in-in** [nostalgic-css/NES.css#255]
**Describe the bug**
The checkbox loses visibility when it is inside a dark container
![v-2019-01-18_23 16 51](https://user-images.githubusercontent.com/8797432/51411203-0ecf4180-1b78-11e9-8ecd-e5d262de085e.gif)

**To Reproduce**
1. Go to https://nostalgic-css.github.io/NES.css/
1. Add `is-dark` class to container with checkbox
2. Try check/uncheck this checkbox
![190181547843296](https://user-images.githubusercontent.com/8797432/51411408-c19f9f80-1b78-11e9-83dd-4f57adafa8cc.png)

**Expected behavior**
```html
<input type="checkbox" checked="" class="nes-checkbox is-dark">
```
I was expecting a light mark when I added the `is-dark` class to input

**Screenshots**
see above :point_up: 

**Environment:**
 - OS: Linux Mint 19.1 Cinnamon
 - Browser: Firefox 64.0, Chromium 71.0

**Comment by guastallaigor** [comment]
Hello @Ilyeo, I'm going to be busy at work but I can take a look when I get back home. Thank you for your contribution.
