### ISSUE TITLE
Adopt technical restrictions from the NES (less colors!)

### ISSUE THREAD

**Issue by lorenzleutgeb** [nostalgic-css/NES.css#260]
I think that lib uses too many colors. Also it would be nice to enforce other constraints that were required by the NES:

> The system has an available color palette of 48 colors and 6 grays. Up to 25 simultaneous colors may be used without writing new values mid-frame: a background color, four sets of three tile colors and four sets of three sprite colors. The NES palette is based on NTSC rather than RGB values. A total of 64 sprites may be displayed onscreen at a given time without reloading sprites mid-screen.

https://en.wikipedia.org/wiki/Nintendo_Entertainment_System#Technical_specifications

**Comment by BcRikko** [comment]
ref #27

**Comment by guastallaigor** [comment]
To me, leave the colors as it is. I think this comment in issue #5 by @BcRikko applies here:

![image](https://user-images.githubusercontent.com/22016005/53293896-5b332000-37bb-11e9-8f4e-f47c93cea541.png)
