### ISSUE TITLE
Bug: Highlight.js not loading sometimes in index.html (docs)

### ISSUE THREAD

**Issue by guastallaigor** [nostalgic-css/NES.css#293]
**Describe the bug**
Sometimes when opening the [documentation demo website](https://nostalgic-css.github.io/NES.css/), there's no style in the code div.

**To Reproduce**
1. Open [documentation demo website](https://nostalgic-css.github.io/NES.css/);
2. Click on the "show code button";
3. You will see that sometimes the code div has no style at all;
4. You can also check chrome devtools console that appears a `hljs is not defined`.

**Expected behavior**
Everytime the page is opened highlight.js should be loaded.

![image](https://user-images.githubusercontent.com/22016005/52921833-0b0b1800-32fa-11e9-86cf-6f4888480c6e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/22016005/52921758-2cb7cf80-32f9-11e9-9e5e-24689c693b0e.png)

**Environment:**
 - OS: Windows 10 Pro
 - Browser: Chrome Version 72.0.3626.109 64 bits
 - Build environment (i.e. NodeJS): N/A

**Suggestion(s) for fixing this issue**
Change the `<script>` tag or maybe put the `hljs` init inside `window.onload`.

**Additional context**
This could be a hotfix situation.

**Comment by BcRikko** [comment]
I see 🙈 
I fixed it in #292 .
