### ISSUE TITLE
StackOverFlow icon?

### ISSUE THREAD

**Issue by renantins** [nostalgic-css/NES.css#299]

**Comment by renantins** [comment]
An icon for StackOverFlow would be nice

**Comment by BcRikko** [comment]
Thanks for your idea 😆 

but I'm sorry 🙇 
stackoverflow is not a social button, so I can not think of a purpose. 🤔 

If you really need stackoverflow icon, you can create it with https://vue-pixel-art.now.sh/ 👍

**Comment by guastallaigor** [comment]
The only thing I can think of is to use the icon to share your stackoverflow profile by clicking on it.

I've tried to create one once but it didn't look good :smile:, so I dropped it. And then again, I agree with @BcRikko, is not exactly a social icon so is less likely to be used.

**Comment by BcRikko** [comment]
> to share your stackoverflow profile by clicking on it.

Oh, I see 👍 
I didn't know stackoverflow in detail, because I'm lurker. I have not user on stackoverflow😅 

@renantins If you need stackoverflow icon, you can create an icon with the following tool. 🛠 
https://vue-pixel-art.now.sh/

**Comment by renantins** [comment]
@BcRikko For share StackOverFlow story https://stackoverflow.com/users/story/join
