### ISSUE TITLE
Blurred Borders in Safari

### ISSUE THREAD

**Issue by tomma5o** [nostalgic-css/NES.css#301]
🖖 Hi I've found an annoying bug in safari
probably is related to #244 and #273

**Describe the bug**
Blurred borders everywhere is used border-image

**To Reproduce**
See the NES website in Safari

**Screenshots**
![screenshot 2019-02-22 at 11 58 21](https://user-images.githubusercontent.com/8134038/53238279-3181d800-3699-11e9-8760-542ed47cc790.png)

**Environment:**
 - Browser: Safari 12.0

**Suggestion(s) for fixing this issue**
change this
`border-image-repeat: space;`
into
`border-image-repeat: stretch;` this fixes the border relates issue in firefox chrome and safari ;)

**Comment by guastallaigor** [comment]
@tomma5o This is also fixed by #301?
