### ISSUE TITLE
Broken style of elements in Chrome using CDN

### ISSUE THREAD

**Issue by whiteyhat** [nostalgic-css/NES.css#316]
**Describe the bug**
There is an error to render NES-CSS elements using the latest CDN on Google Chrome. The left side of the elements are not well rendered.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [Satoshis.Games](https://satoshis.games)
2. View the elements. Buttons and NES - elements

**Expected behaviour**
Clean elements without resulting in a visual error on the left side of the element.
**Screenshots**
<img width="454" alt="captura de pantalla 2019-02-28 a las 22 25 49" src="https://user-images.githubusercontent.com/31220861/53602875-e8091f80-3ba7-11e9-8077-aff43b9e58ec.png">

<img width="525" alt="captura de pantalla 2019-02-28 a las 22 28 20" src="https://user-images.githubusercontent.com/31220861/53602976-2dc5e800-3ba8-11e9-869c-82ee6945b1f1.png">

**Environment:**
 - Browser: Google Chrome. On safari works great. Firefox/Opera not tested.
 - Build environment (i.e. NodeJS): NodeJS

**Suggestion(s) for fixing this issue**
It probably is a compiling issue regarding Chrome

**Comment by guastallaigor** [comment]
Maybe ref #271, #244. I will try to reproduce later, because at first the buttons that I'm seeing in Satoshis.Games are fine, but I haven't found those bugs from your screenshots yet.

**Comment by whiteyhat** [comment]
I have updated to the latest version and tested locally.

It seems like the browser was zoomed at 90%, and this caused the issue.

> Are you the owner of this website?

Yeah 👍
