### ISSUE TITLE
Weird border on chrome android

### ISSUE THREAD

**Issue by kefniark** [nostalgic-css/NES.css#317]
**Describe the bug**
On **chrome 72**, everything looks OK on desktop.

![image](https://user-images.githubusercontent.com/4903529/53685305-192a5100-3d5c-11e9-822e-3e977c2b865d.png)

But on mobile, even with the same version of chrome the border looks really bad.

![screenshot_20190303-022400_chrome](https://user-images.githubusercontent.com/4903529/53685308-247d7c80-3d5c-11e9-80b4-f2977977ff1c.jpg)

**To Reproduce**
* Open the the [public page](https://nostalgic-css.github.io/NES.css/) with an android phone.
* I was able to reproduce it with:
  * Samsung galaxy s8
  * Google nexus
  * Google pixel

**Expected behavior**
To look the same than the Desktop version

**Screenshots**
![image](https://user-images.githubusercontent.com/4903529/53685356-cb621880-3d5c-11e9-9be1-ec5b96fbe9ed.png)

**Environment:**
 - OS: Android
 - Browser: Chrome

**Comment by kefniark** [comment]
looking at my first screenshot, I noticed something else strange with `<select>` ...

 * on desktop, when I use the fullscreen API, the `<select>` arrow seems to disappear 🤔 (maybe a chrome bug)
 * on mobile the arrow is here but the background color is gray and not white

![image](https://user-images.githubusercontent.com/4903529/53685507-ecc40400-3d5e-11e9-9371-0bc56c23ea1d.png)

**Comment by virtuoushub** [comment]
I am seeing this on Chromium [Version 72.0.3626.119 (Official Build) (64-bit)] Windows. Seems to be related to **is-rounded** class.

**compare Firefox (left) Chromium (right)**
![compare](https://user-images.githubusercontent.com/4303638/53690755-9b0b8180-3d3e-11e9-84c7-9c44eb7078c1.png)

**Chromium**: https://nostalgic-css.github.io/NES.css/
![compare1](https://user-images.githubusercontent.com/4303638/53690756-9b0b8180-3d3e-11e9-9505-46085aea57c7.png)

**Comment by BcRikko** [comment]
ref #244

**Comment by guastallaigor** [comment]
Maybe #319 fix these kind of bugs :pray: . 
But I can't test it in Android Chrome nor Safari :cry:.
