### ISSUE TITLE
Form parts bleed outside of parent container

### ISSUE THREAD

**Issue by alexd99** [nostalgic-css/NES.css#322]
**Describe the bug**

When I use one of the form parts (input, select, and text area) the right border bleeds past the edge of its container. 

**To Reproduce**

1.  Put a form part inside of a container that has a defined width
1.  Put a background color on the parent container
1.  The right border bleeds past the parent container

I have built a code [sandbox](https://codesandbox.io/s/m616xw62j) that demonstrates this behavior.

**Expected behavior**

Form parts should stop at the end of its parent container. 

**Screenshots**

<img width="822" alt="screen shot 2019-03-07 at 8 46 24 am" src="https://user-images.githubusercontent.com/31349451/53969175-89670880-40b5-11e9-8f28-f0f5b7e83cd5.png">

**Environment:**

 - OS: Mac Mojave (10.14.3)
 - Browser: Google Chrome (72.0.3626.121)

**Comment by runyasak** [comment]
I have PR to fixed this case by width from nes-input to let it stretch to parent tag.
Please, review and see more information from this #326

**Comment by thisisabhinay** [comment]
Since, PR https://github.com/nostalgic-css/NES.css/pull/327 is waiting for contributor since April. I've fixed the issue as per suggestion by @BcRikko .
