### ISSUE TITLE
Add a way to access the pointer cursor

### ISSUE THREAD

**Issue by alexd99** [nostalgic-css/NES.css#339]
**Is your feature request related to a problem? Please describe.**

The feature request is not related to a problem with the framework. With the app, I am building I want to add a pointer cursor on hover, but I can't easily access the pointer cursor that this framework uses. 

**Describe the solution you'd like**
An easy way to get access to the pointer cursor that this framework uses. Maybe via a css class like`nes-pointer`

**Describe alternatives you've considered**
The way I am currently getting passed this is by adding:
`cursor: url(https://unpkg.com/nes.css@latest/assets/cursor-click.png), auto;`
to the element that I want to have the pointer cursor

I would be happy to work on this if others are interested in the idea. The only issue is I'm not sure what file something like this would belong in.

**Comment by guastallaigor** [comment]
Yes I had  this problem too and I'm on board with the idea of having an easier way to access the cursor 👍. What do you think @BcRikko?

**Comment by BcRikko** [comment]
I see. That's true. 🙆‍♂ 
I agree to provide `nes-pointer` ☝️ 

Like this? 🤔 
```html
<!-- Change the cursor on hover -->
<div class="nes-pointer"></div>
```
```
./scss
   |- helpers
      |- pointer.scss
```
```scss
.nes-pointer {
  cursor: $cursor-click-url, pointer;
}
```
---

Here's an article: [Buttons shouldn’t have a hand cursor – Simple = Human – Medium](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b)

I understand this article to some extent. 🤔 
However, this is not an issue of the CSS Framework, but an issue for developers.
Please remember that there is an argument like this. 👍
