### ISSUE TITLE
Add Ballons dark mode

### ISSUE THREAD

**Issue by guastallaigor** [nostalgic-css/NES.css#345]
**Is your feature request related to a problem? Please describe.**
I propose to create a Balloons `is-dark` class, similar to the other components, because we are missing just a few components that doesn't have the `is-dark` class.

**Describe the solution you'd like**
Something similar to the containers, tables or dialogs.
After creating, add it to the docs as well.
I don't have a draft for this yet.

**Describe alternatives you've considered**
Don't add it at all.

**Additional context**
Maybe add this after #331.

**Comment by youngkaneda** [comment]
@guastallaigor i could do this today if not exist an already PR for this.

**Comment by guastallaigor** [comment]
@youngkaneda Great, thank you :smile:. I don't think there's anyone working in this at the moment, so no PRs :+1:

**Comment by hovi** [comment]
Hey guys, any progress on this?

**Comment by guastallaigor** [comment]
I'm not sure. I haven't tried anything myself.

**Comment by HiKaylum** [comment]
I have created a PR for this.

Also sorry for the ref comments 😅ran into branching / commit issue due to being a spud!
