### ISSUE TITLE
Publish components seperately

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [nostalgic-css/NES.css#346]
**Describe the solution you'd like**
I want to create a components library with Web Components, that's based on NES.css, but now I have to load the complete library into every component, which is not optimal and results in bulky packages. I would like to see that all components are published as separate (scoped) packages.

**Describe alternatives you've considered**
Include the complete NES.css library into every component I create.

**Comment by BcRikko** [comment]
> I want to create a components library with Web Components, that's based on NES.css

Thanks 👍 


We publish the two files. 📦 

* nes-core.css (nes-core.min.css)
   * only component styles
   * about 50KB
* nes.css (nes.min.css)
   * included pixel icons and pixel arts.
   * about 280KB

If you use scss, you can import components like `@import "~nes.css/scss/elements/buttons.scss";`. 🤔

**Comment by StefanNieuwenhuis** [comment]
I'm gonna try it out! Thanks.

**Comment by BcRikko** [comment]
ref #284
