### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Flip32** [nostalgic-css/NES.css#374]
Hi, I've just used this, in a new project. It's just for learning, but I let my friends used too.
I'd like to know if I have to put something inside my project, like a link to your repository or if I have to say that it's not belong to me, or something like that.

**Comment by guastallaigor** [comment]
Hello. This project follows the [MIT](https://github.com/nostalgic-css/NES.css/blob/develop/LICENSE) License. 
In my opinion, other than that, you can put a reference to NES.css if you want, but you don't have to.

I will keep this issue open for a while if anyone else would like to say or add anything else to this 👍

**Comment by BcRikko** [comment]
@guastallaigor , I agree with you 👍 

@Flip32 Enjoy using NES.css 🎮 
And if you think NES.css is a good product, I would apprecate it if you could recommend it to everyone around you. 😆
