### ISSUE TITLE
Recommended environment for CONTRIBUTING.md

### ISSUE THREAD

**Issue by Takumi0901** [nostalgic-css/NES.css#379]
**Describe the bug**

Setup error when using node v13.x
If I tried node v12.x or below, setup is complete.
I wanted to describe the recommended environment for node and npm.

**Environment:**
 - OS: Mac OSX
 - Browser: 
 - Build environment (i.e. NodeJS): node v13.2.0

**Comment by BcRikko** [comment]
Thanks for your report 🙇 

I agree with writing a Node version on CONTRIBUTING.md. 👍 
As I confirmed with node 10.x and 12.x version, I want to change the package.json as well.

ref #367
