### ISSUE TITLE
Examples section

### ISSUE THREAD

**Issue by andreasvirkus** [nostalgic-css/NES.css#38]
Hi, 

First off, loving this framework ❤️ !

Would you consider adding an examples section to the readme, where people could link their
projects/websites that use this framework? I bet there are/will be a lot of cool things built with it :)
(e.g. we're building a space-invaders game for our 404 page with NES.css)

**Comment by BcRikko** [comment]
Thanks ❤️ 

OK, I'll write 👍

**Comment by evexoio** [comment]
@andreasvirkus can you share your 404 page once it's done please? 🙏

We still don't have a lot of sites using our framework, your 404 page is a nice use-case to motivate other to use our framework 🙌

**Comment by evexoio** [comment]
@TangibleDream [We don't have enough people using our frameworks](https://github.com/nostalgic-css/NES.css/pull/119#issuecomment-447670695) to have an examples page yet.

But keep an eye on this thread, if we get @andreasvirkus's website, and at least 2 more, feel free to open a PR for this 🙌

We already have https://logo-maker.egoist.sh using us :)

So let's say 3-4 examples to open a PR, and then we can make a page that gives us some credibility.

**Comment by andreasvirkus** [comment]
Slow progress on our error/game page atm, but I just discovered also that Croak.io is using you guys ❤️ 

https://croak.io/
https://croak.io/games/croak
https://croak.io/blog/components-in-vue

**Comment by martinsoender** [comment]
@andreasvirkus @BcRikko @evexoio 

First of all thanks for doing this super cool project. I've been trying to find an e-mail to get in touch with any of the core team contributors. But without any luck. Absolutely in love with the old school style.

Saw this post today - so worked out a couple of pages using your components for an example page.   worked a bit on different pages. [View my result here](https://take.ms/1Ca9D)

If you are interested I'm more than happy to become a contributor and push this project to greater heights. 

Best 
Martin

**Comment by elbenjaz** [comment]
> @andreasvirkus @BcRikko @evexoio
> 
> First of all thanks for doing this super cool project. I've been trying to find an e-mail to get in touch with any of the core team contributors. But without any luck.
> 
> Saw this post today - so worked out a couple of pages using your components as examples. [View my result here](https://take.ms/1Ca9D)
> 
> I'm more than happy to become a contributor and push this project to greater heights.

Hi, nice video,
Could you publish the source code of those templates?
Good job :)

**Comment by martinsoender** [comment]
> Hi, nice video,
Could you publish the source code of those templates?
Good job :)

@elbenjaz I've created repo for the examples shown in the video. You can find it [here](https://github.com/martinsoender/NES.css-examples). 
It's pretty basic without any preprocessors. :)

**Comment by elbenjaz** [comment]
> > Hi, nice video,
> > Could you publish the source code of those templates?
> > Good job :)
> 
> @elbenjaz I've created repo for the examples shown in the video. You can find it [here](https://github.com/martinsoender/NES.css-examples).
> It's pretty basic without any preprocessors. :)

Thanks a lot, it looks great :D

**Comment by martinsoender** [comment]
@elbenjaz You are very welcome. Will update on occasions :)

**Comment by andreasvirkus** [comment]
I know #119 mentions that we'd to list a minimum of 5 sites using NES.css, so I'm just adding one to the list - Twilio's [Open Pixel Art]https://open-pixel-art.com/) project uses us! 🎉
