### ISSUE TITLE
No styles for list disks/circles on a dark background

### ISSUE THREAD

**Issue by ghost** [nostalgic-css/NES.css#397]
Hey! I like your library a lot. But I noticed a little problem (at least for me)
**Is your feature request related to a problem? Please describe.**

List disks don't have an option to be placed on a dark bg, cause they are always dark.
**Describe the solution you'd like**

Please, add white disk lists :)
**Describe alternatives you've considered**

**Additional context**

**Comment by guastallaigor** [comment]
Hello @ellenripley4.
I think this is a duplicated from #395 which was fixed on #396 in our `develop` branch, and will be available in the next release.
Please, take a look and if you have any questions or additional suggestions, just let me know.
Thank you.

**Comment by ghost** [comment]
Thanks @guastallaigor for pointing this out!
