### ISSUE TITLE
can this project support chinese character？

### ISSUE THREAD

**Issue by luengwaiban** [nostalgic-css/NES.css#398]
**Is your feature request related to a problem? Please describe.**
First of all, my english is not good so if anything below offense you, forgive me ...
I am a chinese developer，and I found there's no chinese character supported. So I am here to request support.

**Describe the solution you'd like**
Support the chinese chatacter like jp chatacter.....

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by BcRikko** [comment]
No problem 👍 

> NES.css doesn't provide any fonts, but we do maintain the following list of fonts that we recommend for usage alongside the library.
> https://github.com/nostalgic-css/NES.css#fonts

So if you know any 8-bit like Chinise fonts and would like to recommend it to other Chinese developers, Please let me know the font.

And if you can, please update README.md and send us a Pull Request. 🙏

**Comment by luengwaiban** [comment]
@BcRikko yes you can checkout this link and download the chinese font in pixel art style

https://en.fontke.com/font/20173482/

But I am not sure weather it is 8-bit or not. And I am not good at css, too.   Really sorry for that....

**Comment by guastallaigor** [comment]
Closing because of #406
