### ISSUE TITLE
Cannot install nes.css with latest node versions

### ISSUE THREAD

**Issue by doliG** [nostalgic-css/NES.css#414]
**Describe the bug**
```
❯ yarn add nes.css@latest
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error nes.css@2.3.0: The engine "node" is incompatible with this module. Expected version "10.x". Got "13.11.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**To Reproduce**
1. Install node > 13
2. Try to install nes.css via yarn

**Expected behavior**
The installation works.

**Environment:**
 - OS: MacOS Mojave
 - Build environment (i.e. NodeJS): Node 13

**Suggestion(s) for fixing this issue**
Well, I manage to install nes.css with downgrading my node version to 10.19.0. However, this is not a fix, but a workaround.

Looks like the solution is here: https://github.com/nostalgic-css/NES.css/issues/392#issuecomment-569440614

I can create a PR is you want.

**Comment by BcRikko** [comment]
Currently, NES.css is using `node-sass@4.12.0`. The reason you can't install NES.css is in `node-sass`. (https://github.com/nostalgic-css/NES.css/issues/392#issuecomment-569440614)

> I can create a PR is you want.

Yeah 👍 
I'd appreciate it if you could send a PR to this repository.
Probably just upgrading the version of `node-sass` to `4.13.x`. 🤔

**Comment by candywater** [comment]
Small problem but a little different

Cannot install nes.css via yarn, node version is 12.13.0
but can install nes.css via npm, node version is 12.13.0

here is yarn __error__ message
```
[1/4] Resolving packages...
[2/4] Fetching packages...
error nes.css@2.3.0: The engine "node" is incompatible with this module. Expected version "10.x". Got "12.13.0"
error Found incompatible module.
```

here is npm **warning** message
```
npm WARN saveError ENOENT: no such file or directory, open '/mnt/e/work_space/learning/nes/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for nes.css@2.3.0: wanted: {"node":"10.x"} (current: {"node":"12.13.0","npm":"6.12.0"})
npm WARN notsup Not compatible with your version of node/npm: nes.css@2.3.0
npm WARN enoent ENOENT: no such file or directory, open '/mnt/e/work_space/learning/nes/package.json'
npm WARN nes No description
npm WARN nes No repository field.
npm WARN nes No README data
npm WARN nes No license field.

+ nes.css@2.3.0
added 1 package from 1 contributor and audited 1 package in 6.594s
found 0 vulnerabilities
```

**Comment by doliG** [comment]
@candywater Thanks for the informations. This is, indeed, weird.

Maybe yarn and npm have different strategies to handle _unsupported engine_, where yarn raise an error and stop, npm just show a warning and try to do it anyway 🤔

**Comment by ghost** [comment]
same problem

**Comment by virtuoushub** [comment]
@doliG / @candywater yes `yarn` is a bit more strict in that it will bomb w/ unsupported engines by default.

To get around this you can use: [`yarn install --ignore-engines`](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-ignore-engines).
