### ISSUE TITLE
The use of SNES controller for NES.css 

### ISSUE THREAD

**Issue by michaelmano** [nostalgic-css/NES.css#432]
Your logo is a super nintendo controller for a library named nes, not really a bug but a valid point.

**Comment by BcRikko** [comment]
> Why is the icon of NES.css SNES/SFC?
> https://medium.com/@bc_rikko/why-i-created-and-released-nes-css-ee8966bacd09#adf2

ref #5
ref #32

For these reasons, I used icon like SNES Controller on NES.css logo.
