### ISSUE TITLE
Adding Korean translation of CONTRIBUTING.md

### ISSUE THREAD

**Issue by tank3a** [nostalgic-css/NES.css#464]
I found there are no documentations translated in Korean, and if I can, I'll be willing to contributing on making ko-translated documents, starting from CONTRIBUTING.md.

**Comment by guastallaigor** [comment]
Hello @tank3a , thank you for your message.
To be honest with you, we are not working actively on this project for a while now.
I've been trying to maintain it from time to time, however I don't have access/authorization to accept new features or publish new releases.
So you could create it, however I could only merge it to the `develop` branch, and not sure when we could merge it to `master`.
I do apologize, but I don't think there's much more I can do here.
Thank you again.

**Comment by tank3a** [comment]
@guastallaigor oh thank's for your comment and I'm sorry to hear that. Actually I've already made the Korean translation. As this is my first contribution to the open source, even if it cannot be merged to master right now.. I feel this is also awesome experience and want to PR.
Again I really appreciate your comment even on "discontinued(I guess?)", explaining me how this project is going on, and your help.

**Comment by guastallaigor** [comment]
@tank3a Sure thing. I've already reviewed your PR, after fixing the commit message I can merge it.
Thank you for your understanding.

**Comment by guastallaigor** [comment]
ref #465
