### ISSUE TITLE
Adding font for Arabic

### ISSUE THREAD

**Issue by ZOUHEIRBN** [nostalgic-css/NES.css#496]
I think this font (Paxalah) could be a good variant for Arabic characters
https://ifonts.xyz/paxalah-arabic-font.html

**Comment by abdallahalsamman** [comment]
@ZOUHEIRBN Yes, it looks good!

The font is a [paid font](https://creativemarket.com/mabasiry/1261471-Paxalah-Arabic-Font?utm_source=Link&utm_medium=CM+Social+Share&utm_campaign=Product+Social+Share&utm_content=Paxalah%2C+Arabic+Font+%7E+Non+Western+Fonts+on+Creative+Market), and we already have a bit of direction on how to add custom fonts [here](https://github.com/nostalgic-css/NES.css#usage).

Thank you for the suggestion.
