### ISSUE TITLE
Create a community communication channel

### ISSUE THREAD

**Issue by trezy** [nostalgic-css/NES.css#57]
Another nice way to facilitate building a community around a project like this is to create a channel through which the community can discuss, brainstorm, and ask for support. I prefer [Gitter](https://gitter.im) for OSS projects, but something like a Slack workspace or a Discord server would work as well. 

I’d also recommend starting to build a team to help you manage the project. Create an organization (I’d call it `old-school-css`, personally, but maybe that’s just me 🙃), transfer the repo to the organization, then start betting community members via the new chat channel. I’m suggesting this, so obviously I’d love to join that team, but it’s ultimately gonna be up to you. 😉

**Comment by trezy** [comment]
Heh, you could also call it `OSOSCSS` (Open Source Old School CSS). 🤣

**Comment by IngwiePhoenix** [comment]
I'd love to see what happens when people enjoying retro-ized projects come together in a Gitter channel. I'd totally be up to this!

Also yes - at this rate of growth this project is experiencing, having a team might come in handy. I mean, this project did - one way or another - _explode_ :)

**Comment by IngwiePhoenix** [comment]
@trezy OSSOSS: Open Source Software old-school style. ;)

**Comment by BcRikko** [comment]
I prefer Slack, because I use Slack on my work. 👨‍💼 
I like simple and easy to understand workspace name. 🤔

**Comment by BcRikko** [comment]
Thanks, I see 🙇 

> but it does make it more of a pain-in-the-butt for community members to join since they need to either be invited or we need to set up an auto-inviter.

Sorry, I didn't know 😇 
If so, Gitter is better 👍 

> And yeah, a simple name would be great. My original suggestion, old-school-css, was intended to be inclusive of potential future products, such as SNES.css, Sega-Genesis.css, and Atari.css. 😁

Oh, great 😄 
Is this include? -> https://github.com/98mprice/PSone.css (Playstation 1 style CSS Framework, inspired by NES.css)

`old-school-css` is good 👍 
I think that `nostalgic-css` is good too. ❤️ 

> That'd just make it easier to have other people help you out with things like reviewing PRs and responding to issues. 😉

I see, thanks sooo mush 😂

**Comment by trezy** [comment]
> If so, Gitter is better 👍

Again, it's your repo so which chat channel you set up is 100% up to you. I don't want you to feel like you're being pressured into Gitter. I just want to make sure that you have all of the useful information that I can give you. 😉

> like this? -> https://github.com/98mprice/PSone.css (Playstation 1 style CSS Framework, inspired by NES.css)

First off, great work @98mprice! PSone.css looks fantastic! Second, @BcRikko, how does it feel to be inspiring others to make more frameworks like this? 😁

> `old-school-css` is good 👍
> I think that `nostalgic-css` is good too. ❤️

I like `nostalgic-css` a lot! I'd definitely go with that one. ❤️

**Comment by IngwiePhoenix** [comment]
To add my two cents:

For me, it is much easier to loose track of a conversation of community in Slack, because there are just so many different teams and places that I'd have to go to in order to keep everything "in sight". Therefore I prefer Gitter, because every group is in one place, as well as every direct message too. Thus - you can log in with your Github! (I mean, it _is_ called *Git*ter after all...)

I'd also like to vote for `nostalgic-css`. Whilst `old-school-css` sounds cool, it may accidentially point towards "how CSS was done back in the days" instead of "how UIs looked like back in the days", which is not the case for `nostalgic-css`.

**Comment by BcRikko** [comment]
I created https://gitter.im/nostalgic-css 🙏 

I have never use Gitter, so I'm not sure how to use Gitter.
Is this OK? 🤔 

> how does it feel to be inspiring others to make more frameworks like this? 😁

I'll welcome. 👍

**Comment by trezy** [comment]
This is great, @BcRikko! I’ll make a PR to add a Gitter badge to our README tomorrow. 😉

**Comment by 98mprice** [comment]
> 
> > like this? -> https://github.com/98mprice/PSone.css (Playstation 1 style CSS Framework, inspired by NES.css)
> 
> First off, great work @98mprice! PSone.css looks fantastic! Second, @BcRikko, how does it feel to be inspiring others to make more frameworks like this? 😁
> 

Thank you all ☺️ & I agree- a community channel is a great idea, I'll be sure to follow the conversation on Gitter.
