### ISSUE TITLE
Add prefix to class name

### ISSUE THREAD

**Issue by BcRikko** [nostalgic-css/NES.css#6]
## ⚠️Breaking changes⚠️ 

Since NES.css doesn't provide layout. It maybe conflict when NES.css using the common class name.
Maybe add a prefix like ns- or nes- to solve this.

レイアウト関連のスタイルは提供していないためユーザ任せになる。そのときにNES.cssで汎用的なクラス名を使っているとコンフリクトする可能性がある。

`ns-`、`nes-`みたいなprefixをつけてコンフリクトを解消したい 🤔 

```html
<!-- ユーザ定義（.container） -->
<section class="container">
    <!-- NES.css (.ns-container.with-title) -->
    <section class="ns-container with-title">
    </section>
</section>
```

**Comment by DanSnow** [comment]
Translation:

Title: Add prefix to class name

Body:

Since NES.css doesn't provide layout. It maybe conflict when NES.css using the common class name.
Maybe add a prefix like `ns-` or `nes-` to solve this.

**Comment by BcRikko** [comment]
@DanSnow Thanks for translate 🙇

**Comment by IngwiePhoenix** [comment]
"ns-" would not be a good choice - it may be confused with "ms" when reading, whilst not paying attention. I suggest either "nes" or "ncss" or "8bit".

**Comment by trezy** [comment]
`.8bit-selector` is an invalid selector, since CSS selectors can't start with a digit. `.nes-selector` would be a good one, though, as it's not used by any other major CSS libraries.

**Comment by BcRikko** [comment]
OK, `nes-` 👍 

For example...
```html
<button class="nes-button is-primary"></button>

<section class="nes-container is-rounded with-title"></section>

<i class="nes-icon heart is-large"></i>

<div class="nes-field">
  <input class="nes-input is-success">
</div>
```

**Comment by IngwiePhoenix** [comment]
Yes, I’d agree on that. :)

**Comment by BinaryMoon** [comment]
I'd suggest everything should have a prefix. is-large, is-primary etc could all be classes used in other libraries.

**Comment by trezy** [comment]
Another option we could eventually look into is allowing users to generate their own version of the library. This idea comes from the [Brototype][brototype] library. There's a companion to that library, [Bro-tie][brotie], that allows the user to do just that.

It's certainly not something we need to bother with while the framework is still in such an early stage, but it would certainly be a fun option to provide. Either way, I agree that we should be fine if we add the prefix to the main classes, then we leave the modifiers as they are.

[brotie]: https://pepperthecat.github.io/brotie/
[brototype]: https://github.com/letsgetrandy/brototype
