### ISSUE TITLE
More icons

### ISSUE THREAD

**Issue by JMGama** [nostalgic-css/NES.css#65]
Is there any way we can get more social-media icons? Like Gmail, Youtube, and phone number? :heart: 
Or how can i make it?

- [X] Medium
- [X] Twitch
- [X] Google
- [X] Youtube
- [x] Phone

**Comment by BcRikko** [comment]
I welcome adding icons 👍 

but The icon increases the size of CSS file. 😭 
so I might divide the icons into different project -> #59

**Comment by guastallaigor** [comment]
What do you guys think of this? Not sure if it's ok.

![image](https://user-images.githubusercontent.com/22016005/49408615-25464880-f744-11e8-8531-914053316677.png)

This supposed to be a youtube icon.

**Comment by BcRikko** [comment]
💯 🙆 🎉

**Comment by guastallaigor** [comment]
![image](https://user-images.githubusercontent.com/22016005/49409251-ed8cd000-f746-11e8-9945-226004be841d.png)

This linkedin one looks a lot uglier but not sure how to improve it.

**Comment by BcRikko** [comment]
@guastallaigor  How is this? 🤔 
https://www.brik.co/blogs/pixel-art/linkedin-pixel-art-1

**Comment by guastallaigor** [comment]
Like this?

![image](https://user-images.githubusercontent.com/22016005/49409739-0d24f800-f749-11e8-8142-c606573f28e0.png)

**Comment by JMGama** [comment]
I already did it, do i need to add something in the css? because it isn't showing.

**Comment by JMGama** [comment]
I did the scss but don't understand what i need to change or add in the css :disappointed:

**Comment by BcRikko** [comment]
1. create icon matrix and color list( like this https://github.com/BcRikko/NES.css/blob/master/scss/icons/like.scss )
2. import `{youricon}.scss` into [icons.scss](https://github.com/BcRikko/NES.css/blob/master/scss/icons/icons.scss)
3. Define a css class ( like this https://github.com/BcRikko/NES.css/blob/master/scss/icons/icons.scss#L78-L80 )
4. add example icon to [index.html](https://github.com/BcRikko/NES.css/blob/master/index.html#L194-L196)
5. build css ( `npm run build` )

I think that it will be showing.

**Comment by guastallaigor** [comment]
> Like this 😆
> ![2018-12-04 9 22 44](https://user-images.githubusercontent.com/5305599/49409973-332cb580-f7a6-11e8-8bc3-9e87f6fe8b11.png)
> 
> ```scss
> $icon-linkedin: (
>   (0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0),
>   (2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2),
>   (2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2),
>   (2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2),
>   (2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2),
>   (2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2),
>   (2,2,1,1,1,2,1,1,1,2,1,1,1,2,2,2),
>   (2,2,1,1,1,2,1,1,1,1,1,1,1,1,2,2),
>   (2,2,1,1,1,2,1,1,1,1,1,1,1,1,2,2),
>   (2,2,1,1,1,2,1,1,1,1,2,1,1,1,2,2),
>   (2,2,1,1,1,2,1,1,1,2,2,1,1,1,2,2),
>   (2,2,1,1,1,2,1,1,1,2,2,1,1,1,2,2),
>   (2,2,1,1,1,2,1,1,1,2,2,1,1,1,2,2),
>   (2,2,1,1,1,2,1,1,1,2,2,1,1,1,2,2),
>   (2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2),
>   (0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0),
> );
> ```
> 
> Would it be better not to resemble the image just before? 🤔
> because [this Image](https://www.brik.co/blogs/pixel-art/linkedin-pixel-art-1) is charged... 😢

This looks better than mine, when you can add this icon ok  👍

**Comment by JMGama** [comment]
This is the Gmail icon i made :smile: 
![image](https://user-images.githubusercontent.com/25947269/49411761-c4147a00-f72f-11e8-8cb7-77b2cc9a98fe.png)
```
$icon-gmail-colors: (#fff, #fd2b2b);
$icon-gmail: (
  ( 0,2,1,1,1,1,1,1,1,1,1,1,1,1,2,0 ),
  ( 2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2 ),
  ( 2,2,2,2,1,1,1,1,1,1,1,1,2,2,2,2 ),
  ( 2,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2 ),
  ( 2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,2 ),
  ( 2,2,2,1,2,2,2,1,1,2,2,2,1,2,2,2 ),
  ( 2,2,2,1,1,2,2,2,2,2,2,1,1,2,2,2 ),
  ( 2,2,2,1,1,1,2,2,2,2,1,1,1,2,2,2 ),
  ( 2,2,2,1,1,1,1,2,2,1,1,1,1,2,2,2 ),
  ( 2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2 ),
  ( 2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2 ),
  ( 2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2 ),
  ( 2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2 ),
  ( 2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2 ),
  ( 2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2 ),
  ( 0,2,2,1,1,1,1,1,1,1,1,1,1,2,2,0 )
);
```

**Comment by BcRikko** [comment]
Good 👍 

I fixed it a little bit. 🛠 
![2018-12-04 10 27 14](https://user-images.githubusercontent.com/5305599/49412268-30828e00-f7af-11e8-8aa1-bee1ff557d4f.png)
```scss
$icon-gmail-colors: (#eeecec, #fd2b2b);
// prettier-ignore
$icon-gmail: (
  (0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
  (0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
  (2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2),
  (2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2),
  (2,2,2,2,1,1,1,1,1,1,1,1,2,2,2,2),
  (2,2,1,2,2,1,1,1,1,1,1,2,2,1,2,2),
  (2,2,1,1,2,2,1,1,1,1,2,2,1,1,2,2),
  (2,2,1,1,1,2,2,1,1,2,2,1,1,1,2,2),
  (2,2,1,1,1,1,2,2,2,2,1,1,1,1,2,2),
  (2,2,1,1,1,1,1,2,2,1,1,1,1,1,2,2),
  (2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2),
  (2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2),
  (2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2),
  (2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2),
  (0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
  (0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
);
```

**Comment by jjspace** [comment]
I would recommend rounding the corners of that gmail logo a bit. It would match the actual logo better and be more in line with the style of all the others you've created
