### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by IngwiePhoenix** [nostalgic-css/NES.css#7]
Hello!

I found this repo in the "trending" section of Github explore - and I cant help it, but I _love_ 8-bit styled things (graphics, sounds - everything!). So I would like to make a couple feature requests, because I actually would like to design my personal blog/website-thing with 8-bit style graphics - and this would fit in just so perfectly! So:

1. Is there a method to use black-on-white by default, such as shown on the `-dark` containers?
2. I would like to request progress bars, or any kind of process indicator really.
3. What about modals/dialog boxes?
4. This is not exactly a feature request, but some more icons would be nice!

Also, I can not read japanese, unfortunately (although I will attend class next year to learn it). So it would be nice if the README was equivalently in english and japanese - most of it is currently not translated. If you would like, I can correct your english spelling/wording properly in the README when you translated it.

Kind regards,
Ingwie!

**Comment by BcRikko** [comment]
Thanks :+1: 

> Is there a method to use black-on-white by default, such as shown on the -dark containers?

Is request to prepare two kinds of themes? (default white theme, and dark theme)
Or to black-and-white(monochrome)?
It's difficult to create theme. but, I'll try my best 😄 

> I would like to request progress bars, or any kind of process indicator really.
> What about modals/dialog boxes?
> This is not exactly a feature request, but some more icons would be nice!

OK, good ideas.


Sorry, I'm not very good at English.
so, translation to English is delayed.

> If you would like, I can correct your english spelling/wording properly in the README when you translated it.

It's really helpful to me.
I would like you to review my English when English docs is finished. 🙇

**Comment by IngwiePhoenix** [comment]
> Is request to prepare two kinds of themes? (default white theme, and dark theme)
> Or to black-and-white(monochrome)?
> It's difficult to change theme. but, I'll try my best 😄

Well basically, it'd be nice to be able to make a white text on black background version. Like when setting the `<body>`-element's class to something like `nes-dark`, it uses a black background and white text, instead of the black text and white background.
 
> Sorry, I'm not very good at English.
> so, translation to English is delayed.

That's absolutely fine with me. I am German myself - so, my english is not that good either. :)

> It's really helpful to me.
> I would like you to review my English when English docs is finished. 🙇

I will definitively do this!

**Comment by BcRikko** [comment]
I understand 👍 
I'll try it.

> I will definitively do this!

🎉 😄 ❤️

**Comment by BcRikko** [comment]
I understand 👍 
I'll try it.
![2018-11-28 11 19 17](https://user-images.githubusercontent.com/5305599/49124379-95496e80-f2ff-11e8-99ab-70dc5271503c.png)

> I will definitively do this!

🎉 😄 ❤️

**Comment by evexoio** [comment]
> Is there a method to use black-on-white by default, such as shown on the -dark containers?
This is done by now.

> I would like to request progress bars, or any kind of process indicator really.
Can you open separate issue for this feature please?

> What about modals/dialog boxes?
Same here. please open a separate issue.

> This is not exactly a feature request, but some more icons would be nice!
Related to #65

**Comment by rodri042** [comment]
@BcRikko how can we use that dark-theme from your screenshot?

**Comment by BcRikko** [comment]
@rodri042 You can use dark-theme with the following code: 

```html
<div class="dark-theme">
  <section class="nes-container is-dark with-title">
     <h2 class="title">Title</h2>
     <p>Hello rodri042!</p>
  </section>
</div>
```
```css
.dark-theme {
  background-color: #202428;
  color: white;
}
```

Some components have `is-dark` class.
So could you check demo page. 👍 
https://nostalgic-css.github.io/NES.css/
