### ISSUE TITLE
Rendering issues with safari.

### ISSUE THREAD

**Issue by evexoio** [nostalgic-css/NES.css#72]
Safari is terrible at rendering NES.css

![dec-04-2018 15-35-25](https://user-images.githubusercontent.com/12014839/49445372-73a62680-f7da-11e8-8060-682634f77dbb.gif)

**Comment by BcRikko** [comment]
What is going on? 😱 
![safari](https://user-images.githubusercontent.com/5305599/49446575-dbc72d80-f817-11e8-8fd4-1a421065a482.gif)

**Comment by BcRikko** [comment]
This code may be the cause. 🤔 
https://github.com/BcRikko/NES.css/blob/1663f704c194818460ad4b2cf7d0cb1e8c25f868/scss/base/generic.scss#L16

I removed `font-smoothing`
![2018-12-04 23 08 53](https://user-images.githubusercontent.com/5305599/49447341-9d327280-f819-11e8-950e-1206a5b4a031.png)

**Comment by jjspace** [comment]
It seems that setting `-webkit-font-smoothing: antialiased` works in safari while still preventing sub-pixel antialiasing to keep those letters crisp :)

**Comment by evexoio** [comment]
@jjspace can you create a PR of that please?

**Comment by dgrcode** [comment]
It seems `-webkit-font-smoothing: none;` doesn't break the styles in Safari, at least in v13.1.1 which I just tested.

In Safari there's very little difference between `none` and `antialiased`, but I see a significant different in Chrome. With `none` it's sharper and cleaner (in my opinion).

Just in case you wanted to reconsider using `-webkit-font-smoothing: none;`
