### ISSUE TITLE
Dark containers font-color broken

### ISSUE THREAD

**Issue by evexoio** [nostalgic-css/NES.css#73]
Dark containers font-color is the same as their background color

<img width="1012" alt="screen shot 2018-12-04 at 5 31 09 pm" src="https://user-images.githubusercontent.com/12014839/49452783-79a40380-f7ea-11e8-895c-d47b2a53ccd5.png">

<img width="1014" alt="screen shot 2018-12-04 at 5 31 52 pm" src="https://user-images.githubusercontent.com/12014839/49452824-92141e00-f7ea-11e8-8a25-281bd05b0126.png">

## Update:
This only happens inside storybook

**Comment by BcRikko** [comment]
duplicate #101
