### ISSUE TITLE
unresponsive on mobile

### ISSUE THREAD

**Issue by YuK1Game** [nostalgic-css/NES.css#8]
checkbox

**Comment by BcRikko** [comment]
I know. 😭 
Responsive design is currently not supported.

**Comment by BcRikko** [comment]
I didn't notice because I don't have ios device. 📱 
<img src="https://pbs.twimg.com/media/DtDZTlcUUAAY_Yw.jpg" width="50%">

**Comment by evexoio** [comment]
This is still an issue, why is it closed?

**Comment by BcRikko** [comment]
It seems that it closed by misoperation, according to YuK1Game.
so I reopen this issue 👐

**Comment by AdrianJVillalobos** [comment]
Is this issue still active? I would like to take this at @NovaHelm

**Comment by guastallaigor** [comment]
I don't think so @AdrianJVillalobos. 
But I mean I only tested it in my IOS so I can't verify that is working in every IOS there is 🤔 
I think the #350 PR fixed it for at least the most 
Sorry for the active issue, I will close it for now but if anyone find a bug in their IOS this issue can be reopen, or can open a new one.

**Comment by AdrianJVillalobos** [comment]
> I don't think so @AdrianJVillalobos.
> But I mean I only tested it in my IOS so I can't verify that is working in every IOS there is 
> I think the #350 PR fixed it for at least the most
> Sorry for the active issue, I will close it for now but if anyone find a bug in their IOS this issue can be reopen, or can open a new one.

@guastallaigor I understand, thanks for answer my comment!
