### ISSUE TITLE
Set up branch protections

### ISSUE THREAD

**Issue by trezy** [nostalgic-css/NES.css#85]
I'd like to get branch protections in place to make sure the project is stable moving forward. I usually set these protections up on both the `master` and `develop` branches. That way, we can prevent PRs from being merged to `develop` without review, and we can require additional CI checks before anything can be merged to `master` (released).

These are the settings I usually set up for both branches. We can, of course, alter the *Require status checks to pass before merging* section for our project. For now, I'd set that to the `ci/circleci: build` and `ci/circleci: lint` checks.

![master-branch-protections](https://user-images.githubusercontent.com/442980/49562882-003c0c00-f8e3-11e8-9336-77a2141a36ff.png)

**Comment by BcRikko** [comment]
I set the `master` and `develop` to the same settings as above image 👍 
Please let me know if It's wrong. 🙏 

![2018-12-06 21 29 21](https://user-images.githubusercontent.com/5305599/49584260-0d6a0100-f99e-11e8-8d52-3a8a76ab7bb2.png)

**Comment by trezy** [comment]
Everything looks great. Thanks for setting those up! 😁
