### ISSUE TITLE
Add btn-extra-pixelize class

### ISSUE THREAD

**Issue by loo41** [nostalgic-css/NES.css#86]
### btn-dot

![65 jg 8x f 5ut2hf b](https://user-images.githubusercontent.com/28095677/49577169-ca9a3000-f981-11e8-974f-d42ba58503d7.png)

- I added a class btn-dot to make button look better
- I'm using box-shadow to see if it fits the project better

What do you think?
 #87

**Comment by loo41** [comment]
Okay, I'll change it to btn-extra-pixelize

**Comment by vandie** [comment]
Following convention for css classes, as it's a variation, shouldn't it be `btn--extra-pixelize` or `btn--pixelize`.

BEM should really be followed for CSS. (https://css-tricks.com/bem-101/)

**Comment by evexoio** [comment]
@BcRikko BEM concepts look good, I think we should look into them 👍

@vandie thanks for bringing this up :)

**Comment by vandie** [comment]
@evexoio I've created the BEM stuff as a separate issue. Will take a look tonight to see if I can create a PR to change it.

**Comment by evexoio** [comment]
@vandie wait, I don't know if we're going to take BEM seriously yet. @BcRikko is the main css guy here so he knows best if BEM fits NES.css or not 🙏

**Comment by vandie** [comment]
@evexoio of course.

**Comment by BcRikko** [comment]
BEM design is powerful 💪 
but BEM is not my favorite, because class name gets longer 😅 

I'm affected by [bulma](https://github.com/jgthms/bulma), so like [SMACSS design](https://smacss.com/) is adopted in this project. 📝

**Comment by jjspace** [comment]
@BcRikko I personally kinda like BEM since i've started using recently but it doesn't really matter in either direction. The thing that matters is that we are all consistent in our naming. It would be good to add a section to the README under development telling everyone what standard we are using so everyone knows from the start

**Comment by BcRikko** [comment]
Ok 👍 

When we publish **storybook**, I think that the problem about the naming convention will be solved 🎉

**Comment by evexoio** [comment]
This is continued at https://github.com/nostalgic-css/NES.css/pull/105#issuecomment-445265288

**Comment by BcRikko** [comment]
I confirmed 🔍 
It's ok with the following code 👍 
```scss
.btn {
  ...
  border: none;
  ...
}
```

**Comment by BcRikko** [comment]
I'll fix it 👍
