### ISSUE TITLE
`npm run build` script doesn't work because of storybook typo

### ISSUE THREAD

**Issue by otaviopace** [nostalgic-css/NES.css#91]
The command `npm run build` doesn't work because of a typo on `package.json`.

[This](https://github.com/nostalgic-css/NES.css/blob/master/package.json#L7):

```json
    "build": "npm run build:clean && npm run build:stylelint && npm run build:sass && npm run build:autoprefix && npm run build:cleancss && npm run build-storybook",
```

Should be [this](https://github.com/otaviopace/NES.css/blob/fix-build/package.json#L7)

```json
    "build": "npm run build:clean && npm run build:stylelint && npm run build:sass && npm run build:autoprefix && npm run build:cleancss && npm run build:storybook",
```

The name of the `storybook` build script is `build:storybook`, and it is `build-storybook`, which makes the `npm run build` fail.

![screenshot-error-example](https://user-images.githubusercontent.com/15306309/49622612-67c08d00-f9b1-11e8-9108-fd9fa734ccf5.png)

**Comment by trezy** [comment]
Marked as invalid since it's already fixed.
