### ISSUE TITLE
Troublesome commitlint 

### ISSUE THREAD

**Issue by evexoio** [nostalgic-css/NES.css#93]
Since we've added commitlint, I've discussed it being removed.

Here's what I tried to just do a very basic thing:
```
git ci -am "fix: Merge Develop; Add Storybook and Backstopjs tests;"
git ci -am "feat(testing): Merge Develop; Add Storybook and Backstopjs tests;"
git ci -am "feat(testing): Merge Develop and add Storybook and Backstopjs tests"
git ci -am "feat(Testing): Merge Develop; Add Storybook and Backstopjs tests;"
git ci -am "Feat(testing): Merge Develop; Add Storybook and Backstopjs tests;"
git ci -am "feat(testing): Merge Develop and add Storybook and Backstopjs tests" --no-verify
```

Every time once of these got me an error, I tried to modify my commit messages based on the error only to get other errors.

I was done, and I wanted to use `--no-verify` to just skip this linting for commit message, but still, I get an error.
```
husky > prepare-commit-msg hook failed (cannot be bypassed with --no-verify due to Git specs)
```

Do we **REALLY** need this? I see this as anti-productive instead of the other way around.

**Comment by evexoio** [comment]
More on this, still trying to commit
```
  git ci -am "feat(testing): Merge Develop and add Storybook and Backstopjs tests" --no-verify
  git ci -am "feat(test): Merge Develop and add Storybook and Backstopjs tests" --no-verify
  git ci -am "feat(test): Merged Develop and add Storybook and Backstopjs tests" --no-verify
  git ci -am "feat(test): Merged Develop and added Storybook and Backstopjs tests" --no-verify
  git ci -am "feat(test) Merged Develop and added Storybook and Backstopjs tests" --no-verify
```

Every time I commit I get
```
✖   message may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
```

What is the subject anyway?

My point is: this just doesn't feel natural, and its very annoying

**Comment by BcRikko** [comment]
How about making this loose rule? 🤔 
![2018-12-07 18 35 22](https://user-images.githubusercontent.com/5305599/49639653-e15a8880-fa4e-11e8-8810-45140b38d3de.png)

This rule is used in vuejs project.
https://github.com/vuejs/vue/blob/dev/scripts/verify-commit-msg.js

@trezy What do you think? 🤔

**Comment by guastallaigor** [comment]
> More on this, still trying to commit
> 
> ```
>   git ci -am "feat(testing): Merge Develop and add Storybook and Backstopjs tests" --no-verify
>   git ci -am "feat(test): Merge Develop and add Storybook and Backstopjs tests" --no-verify
>   git ci -am "feat(test): Merged Develop and add Storybook and Backstopjs tests" --no-verify
>   git ci -am "feat(test): Merged Develop and added Storybook and Backstopjs tests" --no-verify
>   git ci -am "feat(test) Merged Develop and added Storybook and Backstopjs tests" --no-verify
> ```
> Errors I get are
> 
> ```
> ✖   message may not be empty [subject-empty]
> ✖   type may not be empty [type-empty]
> ✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
> ```
> What is the subject anyway?
> 
> My point is: this just doesn't feel natural, and its very annoying

I don't think you can use upper-case letters anywhere in the commit.
Have you tried this?

feat(test): merged develop and added storybook and backstopjs tests

**Comment by guastallaigor** [comment]
@evexoio Yes I understand, I'm used to commit using upper-case letters aswell, but in this repo I'm trying to get used to commiting using only lower-case letters.

**Comment by evexoio** [comment]
More to this, if you end your commit message with a dot it'll get rejected as well 🤧

**Comment by evexoio** [comment]
> Commits are easy to read

Agreed, I can see that already. and we can keep that the way it is with a less strict rule to achieve balance between commit message's clarity and the ease of actually commiting.

@trezy can we apply the changes @BcRikko suggested in his [comment](https://github.com/nostalgic-css/NES.css/issues/93#issuecomment-445175999) and the changes you suggested(commit titles can start with uppercase characters and end with a dot) as well?

**Comment by trezy** [comment]
@evexoio Absolutely! I’ll take a look at that tomorrow. I’m hosting a big holiday party today.

If anybody wants to look into it sooner, you’ll want to look into `commit-lint` rules to implement the changes to the subject format, and `cz-customizable` to alter the available commit types.

**Comment by 4k1k0** [comment]
Please, could someone explain me how to make a commit from the command line? 

This is what I'm doing:

- Clone my fork
- Change to develop branch
- Make some changes
- Create a new branch
- Adding the modified files to the stage
- Commit

I've trying to do it since this morning but I don't understand husky. According to the docs `git commit -m 'Message'` should do the job, but I keep getting this error message:

    ✖   message may not be empty [subject-empty]
    ✖   type may not be empty [type-empty]
    ✖   found 2 problems, 0 warnings

What I am doing wrong? :worried: 

:bowing_man: :pray:

**Comment by guastallaigor** [comment]
Hello @4k1k0, as up to this moment all messages must be like this `type: msg`.
No dot at the end of the line.
Only lower-case letters.
Example: `feat: add new feature` or `feat(icons): add new icon`
You can also use `npm run commit` that can help you with that

**Comment by 4k1k0** [comment]
Thank you so much! It worked like a charm.

**Comment by evexoio** [comment]
@4k1k0 @guastallaigor actually I merged https://github.com/nostalgic-css/NES.css/pull/144

Upper-case letters are ok now, as well as a dot at the end of a sentence :)
