### ISSUE TITLE
Following convention for css classes, should we modify the css here to follow BEM?

### ISSUE THREAD

**Issue by vandie** [nostalgic-css/NES.css#95]
BEM should really be followed for CSS. (https://css-tricks.com/bem-101/) This ensures a consistant class naming system that would help maintance. 

_Originally posted by @vandie in https://github.com/nostalgic-css/NES.css/issues/86#issuecomment-445198048_

**Comment by BcRikko** [comment]
Thanks for your suggestion 🙇 

I commented on https://github.com/nostalgic-css/NES.css/issues/86#issuecomment-445212814 📝

**Comment by vandie** [comment]
Fair enough.
