### ISSUE TITLE
Remove and ignore css

### ISSUE THREAD

**Issue by evexoio** [nostalgic-css/NES.css#97]
According to this comment https://github.com/nostalgic-css/NES.css/issues/13#issuecomment-443428179

We should remove and untrack css files.

**Comment by trezy** [comment]
Ah, I forgot to check during review, but the `css` folder didn't actually get removed, just ignored. @evexoio, could you make another PR to remove the `css` folder?

**Comment by evexoio** [comment]
@trezy Oops, I force pushed 🙈my bad.

**Comment by evexoio** [comment]
This is not done yet, we need to remove all operations on the folder `css` from package.json 🙈🙈
